   <tr>
     <td colspan="4" align="center" class="lastupdate">&nbsp;</td>
  </tr>
</table>

  <center>
   <br>
   <p>
    <font  size="+2">
     The US$10,000 prize was divided as follows:
    </font>
   </p>
   <table border="0">
    <tr>
     <td>distributed.net</td>
     <td>US$6,000</td>
    </tr>
    <tr>
     <td>The individual who found the key</td>
     <td>US$2,000</td>
    </tr>
    <tr>
     <td>The winning individual's team</td>
     <td>Not applicable</td>
    </tr>
    <tr>
     <td>Free Software Foundation</td>
     <td>US$2,000</td>
    </tr>
   </table>
   <hr>
   <p>
    <font  size="+2">
     How this was determined:
    </font>
   </p>
   <table width="80%" border="0">
    <tr>
     <td>
      <p>
       Each individual participant involved in the effort was allowed to select
       which non-profit he or she would prefer to send the prize money.  Each
       person was given one vote per RC5-64 block submitted.  The non-profit that
       receives the most votes was given 60% of the prize money.
      </p>
      <p>
       For RC5-64, participants voted for distributed.net, itself, to be the
       non-profit that would receive the 60% of the money.
      </p>
      <p>
       Of the remaining 40%, 10% was given to the individual who found the
       key and 10% was given to that person's team.  Since the winning individual
       was NOT on a team when they found the key, they received the entire 20%.
      </p>
      <p>
       The 20% remaining was given to the runner-up non-profit as determined by the
       participant voting.
      </p>
      <p>
       Is everyone confused yet?
      </p>
     </td>
    </tr>
   </table>
   <hr>
   <p>
    <font  size="+2">
     Voting Scoreboard (at the time the key was found)
    </font>
   </p>
   <table>
    <tr bgcolor="#cccccc">
     <td>Non-Profit</td>
     <td align="right">Votes</td>
     <td align="right">Supporters</td>
    </tr>
    <tr>
     <td>distributed.net</td>
     <td align="right">7,952,981,606</td>
     <td align="right">14,739</td>
    </tr>
    <tr>
     <td>Free Software Foundation</td>
     <td align="right">6,727,827,800</td>
     <td align="right">16,150</td>
    </tr>
    <tr>
     <td>Electronic Frontier Foundation</td>
     <td align="right">2,876,387,520</td>
     <td align="right">5,842</td>
    </tr>
    <tr>
     <td>Project Gutenberg</td>
     <td align="right">2,752,827,147</td>
     <td align="right">6,185</td>
    </tr>
    <tr>
     <td>Software in the Public Interest</td>
     <td align="right">918,712,254</td>
     <td align="right">2,178</td>
    </tr>
    <tr>
     <td>EPIC</td>
     <td align="right">129,182,951</td>
     <td align="right">416</td>
    </tr>
    <tr>
     <td>CPSR</td>
     <td align="right">52,550,090</td>
     <td align="right">233</td>
    </tr>
   </table>
   <hr>
   <p>
    <font  size="+2">
     Non-Profit Information and Links
    </font>
   </p>
   <table width="80%">
    <tr>
     <td colspan="2" bgcolor="#ccccc">
      <a href="http://www.cpsr.org"><font  dize="+1" color="#000044">CPSR</font></a>
     </td>
    </tr>
    <tr>
     <td width="20">&nbsp;</td>
     <td>CPSR is a public-interest alliance of computer scientists and others concerned about the impact of computer technology on society. We work to influence decisions regarding the development and use of computers because those decisions have far-reaching consequences and reflect our basic values and priorities.</td>
    </tr>
    <tr>
     <td colspan="2" bgcolor="#ccccc">
      <a href="http://www.epic.org/"><font  dize="+1" color="#000044">EPIC</font></a>
     </td>
    </tr>
    <tr>
     <td width="20">&nbsp;</td>
     <td>EPIC is a public interest research center in Washington, D.C. It was established in 1994 to focus public attention on emerging civil liberties issues and to protect privacy, the First Amendment, and constitutional values. EPIC is a project of the Fund for Constitutional Government. EPIC works in association with Privacy International, an international human rights group based in London, UK and is also a member of the Global Internet Liberty Campaign, the Internet Free Expression Alliance and the Internet Privacy Coalition.</td>
    </tr>
    <tr>
     <td colspan="2" bgcolor="#ccccc">
      <a href="http://www.debian.org/donations.html"><font  dize="+1" color="#000044">Software in the Public Interest</font></a>
     </td>
    </tr>
    <tr>
     <td width="20">&nbsp;</td>
     <td>Software in the Public Interest is a non-profit corporation formed by the developers of the Debian Linux Distribution.  Their goal is to promote and distribute free software.  You can read about their approach in the Debian Social Contract, at <a href="http://www.debian.org/social_contract.html">http://www.debian.org/social_contract.html</a>.  Since its incorporation SPI has expanded to include the Open Hardware Certification program and the Berlin project.  They provided resources and money grants to other free software projects such as GNOME.</td>
    </tr>
    <tr>
     <td colspan="2" bgcolor="#ccccc">
      <a href="http://www.promo.net/pg/"><font  dize="+1" color="#000044">Project Gutenberg</font></a>
     </td>
    </tr>
    <tr>
     <td width="20">&nbsp;</td>
     <td>The recipients of the $8,000 "win" from RC5-56, Project Gutenberg's mission in life is to transcribe all the classics of literature to machine-readable form and release them freely for public use.  Download a good book today!</td>
    </tr>
    <tr>
     <td colspan="2" bgcolor="#ccccc">
      <a href="http://www.eff.org/"><font  dize="+1" color="#000044">Electronic Frontier Foundation</font></a>
     </td>
    </tr>
    <tr>
     <td width="20">&nbsp;</td>
     <td>The Electronic Frontier Foundation is a non-profit civil liberties organization working in the public interest to protect privacy, free expression, and access to public resources and information online, as well as to promote responsibility in new media.</td>
    </tr>
    <tr>
     <td colspan="2" bgcolor="#ccccc">
      <a href="http://www.fsf.org/"><font  dize="+1" color="#000044">Free Software Foundation</font></a>
     </td>
    </tr>
    <tr>
     <td width="20">&nbsp;</td>
     <td>The Free Software Foundation (FSF) is dedicated to eliminating restrictions on copying, redistribution, understanding, and modification of computer programs. They do this by promoting the development and use of free software in all areas of computing---but most particularly, by helping to develop the GNU operating system</td>
    </tr>
    <tr>
     <td colspan="2" bgcolor="#ccccc">
      <a href="http://www.distributed.net/"><font  dize="+1" color="#000044">distributed.net</font></a>
     </td>
    </tr>
    <tr>
     <td width="20">&nbsp;</td>
     <td>distributed.net (or more accurately Distributed Computing Technologies, Inc) is a non-profit venture whose sole focus is to test the limits of distributed computing and quantify the power that can be harnessed by applying the concepts of distributed computing to consumer hardware.</td>
    </tr>   </table>
  </center>
