   <tr>
     <td colspan="4" align="center" class="lastupdate">&nbsp;</td>
  </tr>
</table>

  <center>
   <br>
   <p>
    <font  size="+2">
     The US$10,000 prize was divided as follows:
    </font>
   </p>
   <table border="0">
    <tr>
     <td>Project Gutenberg</td>
     <td>US$8,000</td>
    </tr>
    <tr>
     <td>Jo Hermans (the winner)</td>
     <td>US$1,000</td>
    </tr>
    <tr>
     <td>distributed.net</td>
     <td>US$1,000</td>
    </tr>
   </table>
   <hr>
   <p>
    <font  size="+2">
     How this was determined:
    </font>
   </p>
   <table width="80%" border="0">
    <tr>
     <td>
      <p>
       For RC5-56 there was no voting mechanism to choose a non-profit as there have
       been for subsequent projects.  A single recipient non-profit, Project Gutenberg,
       was selected by the distributed.net staff during the first few months of the
       project.
      </p>
      <p>
       Accordingly, when the key was found, Project Gutenberg received 80% of the prize
       money as had been decided.  The remaining $2,000 was split evenly between the
       winner (Jo Hermans) and distributed.net.
      </p>
     </td>
    </tr>
   </table>
   <hr>
   <p>
    <font  size="+2">
     Non-Profit Information and Links
    </font>
   </p>
   <table width="80%">
    <tr>
     <td colspan="2" bgcolor="#ccccc">
      <a href="http://www.promo.net/pg/"><font  dize="+1" color="#000044">Project Gutenberg</font></a>
     </td>
    </tr>
    <tr>
     <td width="20">&nbsp;</td>
     <td>The recipients of the $8,000 "win" from RC5-56, Project Gutenberg's mission in life is to transcribe all the classics of literature to machine-readable form and release them freely for public use.  Download a good book today!</td>
    </tr>
   </table>
  </center>
