<?
// $Id: config.inc,v 1.1 1999/07/11 19:20:48 nugget Exp $

///////////////////////////
// Database Connectivity //
///////////////////////////

$interface = "TALLY";
$username = "LOGIN";
$password = "PASSWORD";

///////////////////////////
// PHP3 Runtime Settings //
///////////////////////////


///////////////////////////
// Template Files to Use //
///////////////////////////

$html_template_body_top = "templates/body_top.phtml";
$html_template_body_bot = "templates/body_top.phtml";
$html_template_head = "templates/head.phtml";

///////////////////////////
// Layout Style Elements //
///////////////////////////

$bar_color_a = "#dddddd";
$bar_color_b = "#ffffdd";

$fo_default = "<font face=\"arial,helvetica\">";
$fo_fixed   = "<font face=\"lucida console, courier\">";
$fo_h1      = "<font face=\"verdana,arial,helvetica\" size=\"+2\">";
$fo_h2      = "<font face=\"verdana,arial,helvetica\" size=\"+1\">";
$foff       = "</font>";

$co_bgcolor = "#dddddd";
$co_text    = "#000000";
$co_link    = "#222255";
$co_heada   = "#ffffff";
$co_lista   = "#9999cc";
$co_listb   = "#9999bb";
$co_listc   = "#cccccc";


////////////////////////////////
// Number formatting defaults //
////////////////////////////////

$decimal_places = "2";
$number_style = "US";

?>
