<?php
  print "
	<center>
	<table width=\"400\" border=\"0\"><tr><td>
	<h2>There was an error processing your request</h2>
	<p>
	 The server was unable to complete your request.<br>
	 This is most likely due to one of two reasons.  Either the system
	 is offline for the daily update, or Nugget is mucking about in
	 the database again.
	</p>
	<p>
	 Either way, it's probably not anything you should be concerned about.
	 I suggest you head to the kitchen and raid the fridge.  Maybe have a
	 nice loose-meat sandwich and a wholesome glass of milk (&lt;dbaker&gt; or two yummy cans of Dr. Pepper &lt;/dbaker&gt;). 
	</p>
	<p>
	 By the time you're back, the server will probably be finished and
	 you can check your stats.  If it's not, the situation will seem a
	 lot less important if you've got a full stomach.
	</p>
	<p>
	 Thanks for your patience.
	</p></td></tr></table>";
?>
