<?php
  # $Id: plocked.inc,v 1.5 2003/10/23 01:55:43 thejet Exp $

  print "
	<div style=\"text-align: center\">
	<table width=\"400\" border=\"0\"><tr><td>
	<h2>There was an error processing your request</h2>
	<p>
         This email address has been locked.  You may no longer edit this email's information.<br>
         Please contact help@distributed.net if you feel that this is in error.
	</p>
	</td></tr></table></div>";
?>
