<?php
  # $Id: plocked.inc,v 1.4 2000/06/13 20:18:45 decibel Exp $

  print "
	<center>
	<table width=\"400\" border=\"0\"><tr><td>
	<h2>There was an error processing your request</h2>
	<p>
         This email address has been locked.  You may no longer edit this email's information.<br>
         Please contact help@distributed.net if you feel that this is in error.
	</p>
	</td></tr></table>";
?>
