<?php
  # $Id: tmerror.inc,v 1.5 2003/05/27 18:37:21 thejet Exp $

  print "
	<div style=\"text-align: center\">
	<table width=\"400\" border=\"0\" style=\"margin: auto\"><tr><td>
	<h2>There was an error processing your request</h2>
	<p>
	 Since team creation is brand-new code, this shouldn't be too shocking.
	</p>
	<p>
	 Please report the error and the we'll look into it.
	</p>
	<p>
	 Thanks for your patience.
	</p></td></tr></table></div>";
?>
