<?php
  print "
	<center>
	<table width=\"400\" border=\"0\"><tr><td>
	<h2>read-only mode</h2>
	<p>
	 The server was unable to complete your request, as the site is currently 
	 read-only.<br>
	 Thus, all changes to teams, participants, retires, etc. are currently blocked, while we do some work on the server
	</p>
	<p>
	 Check back soon, or watch the <a href=\"http://n0cgi.distributed.net/cgi/dnet-finger.cgi\">.plans</a> for further updates.
	</p>
	<p>
	 Thanks for your patience.
	</p></td></tr></table>";
?>
